"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent


def load_environment_files():
    load_dotenv(REPO_ROOT / ".env", override=False)

    env_file = os.environ.get("ENV_FILE")
    if env_file:
        load_dotenv(REPO_ROOT / env_file, override=False)
        return

    if is_pytest_invocation():
        load_dotenv(REPO_ROOT / ".env.test", override=False)


def is_pytest_invocation():
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return True
    if "pytest" in sys.modules:
        return True
    if not sys.argv:
        return False

    try:
        argv0 = Path(sys.argv[0]).resolve()
    except OSError:
        argv0 = Path(sys.argv[0])

    return argv0.name == "pytest" or "pytest" in argv0.parts


def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ValueError(f"{name} must be a boolean value")


def env_int(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ValueError(f"{name} must be an integer") from exc


def env_float(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return float(value)
    except ValueError as exc:
        raise ValueError(f"{name} must be a number") from exc


load_environment_files()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = ['*']  # Configure appropriately in production


# Application definition

INSTALLED_APPS = [
  "django.contrib.admin",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
  "channels",
  "rest_framework",
  "django_filters",
  "files",
]

MIDDLEWARE = [
  "django.middleware.security.SecurityMiddleware",
  "whitenoise.middleware.WhiteNoiseMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "django.middleware.common.CommonMiddleware",
  "files.middleware.UserIdMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
      ],
    },
  },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgres://filevault:filevault@localhost:5432/filevault",
)
DATABASES = {
    "default": dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    ),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MAX_UPLOAD_SIZE_BYTES = env_int('MAX_UPLOAD_SIZE_BYTES', 10 * 1024 * 1024)
STORAGE_LIMIT_BYTES = env_int('STORAGE_LIMIT_BYTES', 10 * 1024 * 1024)
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY')
ENCRYPTION_CHUNK_SIZE_BYTES = env_int('ENCRYPTION_CHUNK_SIZE_BYTES', 1024 * 1024)
RATE_LIMIT_CALLS = env_int('RATE_LIMIT_CALLS', 2)
RATE_LIMIT_PERIOD = env_float('RATE_LIMIT_PERIOD', 1)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
RAG_EMBEDDING_MODEL = os.environ.get('RAG_EMBEDDING_MODEL', 'text-embedding-3-small')
RAG_EMBEDDING_DIMENSIONS = env_int('RAG_EMBEDDING_DIMENSIONS', 1536)
RAG_CHUNK_SIZE = env_int('RAG_CHUNK_SIZE', 1000)
RAG_CHUNK_OVERLAP = env_int('RAG_CHUNK_OVERLAP', 150)
RAG_RETRIEVAL_K = env_int('RAG_RETRIEVAL_K', 4)
RAG_RETRIEVAL_FETCH_K = env_int('RAG_RETRIEVAL_FETCH_K', 12)
RAG_MAX_CONTEXT_CHUNKS = env_int('RAG_MAX_CONTEXT_CHUNKS', 4)
RAG_MAX_DISTANCE = env_float('RAG_MAX_DISTANCE', 0.35)
RAG_LLM_MODEL = os.environ.get('RAG_LLM_MODEL', 'gpt-4.1-mini')
DEFAULT_PAGE_SIZE = env_int('DEFAULT_PAGE_SIZE', 20)
MAX_PAGE_SIZE = env_int('MAX_PAGE_SIZE', 100)
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Docker Compose sets REDIS_URL for Redis-backed, multi-worker rate limiting.
# SlidingWindowThrottle uses Redis directly for its atomic Lua/ZSET path and
# falls back to this Django cache configuration when REDIS_URL is unset.
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'abnormal-file-vault',
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}
