ACTION_ASK = "ask"
ACTION_SELECT = "select"

FIELD_ACTION = "action"
FIELD_CODE = "code"
FIELD_CHUNKS = "chunks"
FIELD_DATA = "data"
FIELD_FILE_ID = "file_id"
FIELD_FILE_IDS = "file_ids"
FIELD_FILE_TYPE = "file_type"
FIELD_INDEXED_FILES = "indexed_files"
FIELD_METADATA = "metadata"
FIELD_ORIGINAL_FILENAME = "original_filename"
FIELD_PAGE_CONTENT = "page_content"
FIELD_QUESTION = "question"
FIELD_REASON = "reason"
FIELD_SKIPPED_FILES = "skipped_files"
FIELD_SOURCES = "sources"
FIELD_STATE = "state"
FIELD_STORAGE_FILE_ID = "storage_file_id"
FIELD_TYPE = "type"
FIELD_USER_ID = "user_id"
FIELD_CHUNK_INDEX = "chunk_index"

MESSAGE_TYPE_DONE = "done"
MESSAGE_TYPE_ERROR = "error"
MESSAGE_TYPE_NO_ANSWER = "no_answer"
MESSAGE_TYPE_READY = "ready"
MESSAGE_TYPE_STATUS = "status"
MESSAGE_TYPE_TOKEN = "token"

REASON_NOT_IN_DOCUMENTS = "not_in_documents"

STATE_ANSWERING = "answering"
STATE_CONNECTED_NO_DOCUMENTS = "connected_no_documents"
STATE_DISCONNECTED = "disconnected"
STATE_INGESTING = "ingesting"
STATE_READY = "ready"

ERROR_ALREADY_SELECTED = "already_selected"
ERROR_BAD_REQUEST = "bad_request"
ERROR_BUSY = "busy"
ERROR_LLM_FAILED = "llm_failed"
ERROR_NO_DOCUMENTS = "no_documents"
ERROR_NOT_READY = "not_ready"

SKIP_MALFORMED_STORAGE = "malformed_storage"
SKIP_NO_CHUNKS = "no_chunks"
SKIP_NOT_FOUND_OR_NOT_OWNED = "not_found_or_not_owned"
SKIP_UNSUPPORTED_ENCODING = "unsupported_encoding"
SKIP_UNSUPPORTED_TYPE = "unsupported_type"

SUPPORTED_TEXT_MIME_TYPE = "text/plain"

CLOSE_CODE_MISSING_USER_ID = 4401
CLOSE_CODE_BLANK_USER_ID = 4400
