# Generated by Django 4.2.30 on 2026-05-11 14:35

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=128)),
                ('size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('is_reference', models.BooleanField(default=False)),
                ('reference_count', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encryption_iv', models.BinaryField(blank=True, max_length=16, null=True)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='files.file')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id'], name='files_file_user_id'), models.Index(fields=['file_type'], name='files_file_file_type'), models.Index(fields=['size'], name='files_file_size'), models.Index(fields=['uploaded_at'], name='files_file_uploaded_at'), models.Index(fields=['file_hash'], name='files_file_file_hash'), models.Index(fields=['original_filename'], name='files_file_original_filename'), models.Index(fields=['user_id', 'uploaded_at'], name='files_file_user_uploaded_at'), models.Index(fields=['user_id', 'is_reference'], name='files_file_user_is_reference')],
            },
        ),
    ]
