# Generated by Django 4.2.30 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_reference', False)),
                fields=('user_id', 'file_hash'),
                name='files_file_unique_original_hash_per_user',
            ),
        ),
    ]
